app = 'podcodar'
primary_region = 'gru'

[env]
  PHX_HOST = "podcodar.fly.dev"
  PORT = "8080"
  PHX_SERVER = "true"
  DATABASE_PATH = "/data/podcodar.db"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  max_machines_running = 1
  min_machines_running = 1
  processes = ['app']

[vm]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "podcodar_data"
  destination = "/data"
