[tasks]
hello = "echo 'Hello, World!'"
precommit = "mix precommit"
fmt = "deno run -A npm:prettier --write **/*.md"

[env]
_.file = '.env'
_.path = "./node_modules/.bin"
ENV = "production"

[tools]
deno = "latest"
elixir = "latest"
erlang = "latest"
